import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })
import Image from 'next/image'
import layoutTitle from './styles/Layout.module.scss';
export const metadata: Metadata = {
  title: 'Stardew Valley Code Gen',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <Head>
        <link rel="shortcut icon" href='/static/favicon.ico' />
      </Head>
      <body className={inter.className}>
       <div className={layoutTitle.layoutTitle}>
        <Image src='/logo.png' alt='Stardew Valley Codes' width={255} height={143}/>
      </div>
        {children}</body>
    </html>
  )
}
